### ISSUE TITLE
multiple primer parsing (demultiplex.pl)

### ISSUE THREAD

**Issue by jmmack** [ggloor/miseq_bin#23]
For cases when a sequencing run is comprised of different primer sets.

Currently, `demultiplex.pl` finds barcodes by the primer length and the offset. Can we have matching to the primer sequence instead? First by primer, then barcode (to be able to separate different primers+barcodes).

Would it be worthwhile to also report barcode/primer variants with abundant reads that are not in the `samples.txt` file for QC ?

**Comment by ggloor** [comment]
Unfortunately, this would require using approximate sequence matching because the primers can have variation. This was in the first version of the pipeline and was removed because it was very slow.
